name = "big-auth"

compatibility_date = "2024-02-14"
workers_dev = true
route = "http://dev.big.a-kuznetsov.cc/*"

main = "./src/index.ts"
logpush = true

[vars]
TWILIO_SERVICE_SID = 'VA57c51729f8befa0fd3f10073bc2edc1c'


[placement]
mode = "smart"


[env.development]
workers_dev = true

[env.development.vars]
ENV = "development"


[env.production]
workers_dev = false



[env.production.vars]
ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "big"
database_id = "25ae5f05-9c48-4851-bf88-d28ba703b7eb"
preview_database_id = "25ae5f05-9c48-4851-bf88-d28ba703b7eb"
migrations_table = "migrations"
migrations_dir = "src/migrations"

[[r2_buckets]]
binding = 'USER_FILES'
bucket_name = 'user-files'


[durable_objects]
bindings = [{ name = "REFRESH_TOKEN_DO", class_name = "RefreshTokenDO" }]

[[migrations]]
tag = "v1"                       # Should be unique for each entry
new_classes = ["RefreshTokenDO"]



