name = "big-auth"
compatibility_date = "2024-05-11"
main = "./src/index.ts"
logpush = true
tail_consumers = [{ service = "big-auth-tail" }]


[placement]
mode = "off"

[[r2_buckets]]
binding = 'USER_FILES'
bucket_name = 'user-files'
preview_bucket_name = 'user-files-preview'

[[queues.producers]]
queue = "push-queue"
binding = "PUSH_QUEUE"

[env.dev]
workers_dev = true
route = "https://dev.iambig.ai/*"
vars = { ENV = "dev", TWILIO_SERVICE_SID = 'VA57c51729f8befa0fd3f10073bc2edc1c', ORIGIN = "https://dev.iambig.ai", AI_AVATAR_URL = "https://dev.iambig.ai/public/23d6658a2a06538a1b04c56aeb1f1874815f6a7f3853481a29609ca46de57bef" }


d1_databases = [
	{ binding = "DB", database_name = "imbig", database_id = "50a83409-8f4f-49ad-af14-573f33b0b91d", migrations_table = "migrations", migrations_dir = "src/db/migrations" },
]


durable_objects = { bindings = [
	{ name = "REFRESH_TOKEN_DO", class_name = "RefreshTokenDO" },
	{ name = "GROUP_CHATS_DO", class_name = "GroupChatsDO" },
	{ name = "USER_MESSAGING_DO", class_name = "UserMessagingDO" },
	{ name = "DIALOG_DO", class_name = "DialogsDO" },
	{ name = "GPT_DO", class_name = "ChatGptDO" },
	{ name = "PUSH_DO", class_name = "PushDO" },
] }


[env.stage]
workers_dev = false
route = "https://stage.iambig.ai/*"

durable_objects = { bindings = [
	{ name = "REFRESH_TOKEN_DO", class_name = "RefreshTokenDO" },
	{ name = "GROUP_CHATS_DO", class_name = "GroupChatsDO" },
	{ name = "USER_MESSAGING_DO", class_name = "UserMessagingDO" },
	{ name = "DIALOG_DO", class_name = "DialogsDO" },
	{ name = "GPT_DO", class_name = "ChatGptDO" },
	{ name = "PUSH_DO", class_name = "PushDO" },
] }
vars = { ENV = "stage", ORIGIN = "https://stage.iambig.ai", TWILIO_SERVICE_SID = 'VA57c51729f8befa0fd3f10073bc2edc1c', AI_AVATAR_URL = "https://dev.iambig.ai/public/23d6658a2a06538a1b04c56aeb1f1874815f6a7f3853481a29609ca46de57bef" }
kv_namespaces = [
	{ binding = "FILES_KV", id = "f6c5cd0496ad436d84882f01db59ef76", preview_id = "52a4091c72f743fc9b1c3cfe6f647277" },
]
d1_databases = [
	{ binding = "DB", database_name = "iambig-stage", database_id = "3140a7dc-6938-4399-8f0c-1ce2a934e8c6", migrations_table = "migrations", migrations_dir = "src/db/migrations" },
]

[[migrations]]
tag = "v55"
new_classes = [
	"UserMessagingDO",
	"DialogsDO",
	"GroupChatsDO",
	"ChatGptDO",
	"PushDO",
	"RefreshTokenDO",
]
