name = "big-auth"

compatibility_date = "2024-04-03"
route = "https://dev.iambig.ai/*"


main = "./src/index.ts"
logpush = true

kv_namespaces = [
	{ binding = "FILES_KV", id = "f6c5cd0496ad436d84882f01db59ef76", preview_id = "52a4091c72f743fc9b1c3cfe6f647277" },

]
[vars]
TWILIO_SERVICE_SID = 'VA57c51729f8befa0fd3f10073bc2edc1c'
ORIGIN = "https://dev.iambig.ai"

[placement]
mode = "off"

[env.development]
workers_dev = true

[env.development.vars]
ENV = "development"
ORIGIN = "https://dev.iambig.ai"

[env.production]
workers_dev = false


[env.production.vars]
ENV = "production"
ORIGIN = "https://iambig.ai"

[[d1_databases]]
binding = "DB"
database_name = "imbig"
database_id = "50a83409-8f4f-49ad-af14-573f33b0b91d"
migrations_table = "migrations"
migrations_dir = "src/db/migrations"

[[r2_buckets]]
binding = 'USER_FILES'
bucket_name = 'user-files'
preview_bucket_name = 'user-files-preview'


[durable_objects]
bindings = [
	{ name = "REFRESH_TOKEN_DO", class_name = "RefreshTokenDO" },
	{ name = "GROUP_CHATS_DO", class_name = "GroupChatsDO" },
	{ name = "USER_MESSAGING_DO", class_name = "UserMessagingDO" },
	{ name = "DIALOG_DO", class_name = "DialogDO" },
]

[[migrations]]
tag = "v20"
deleted_classes = ["UserMessagingDO","DialogDO"]

[[migrations]]
tag = "v21"
new_classes = ["UserMessagingDO", "DialogDO"]
