name = "big-auth"

compatibility_date = "2024-02-14"
workers_dev = true
route = "http://dev.big.a-kuznetsov.cc/*"

main = "./src/index.ts"


[vars]
TWILIO_SERVICE_SID = 'VAb176f1a570fd06d893498a6af5b55b49'


[placement]
mode = "smart"


[env.development]
workers_dev = true

[env.development.vars]
ENV = "development"


[env.production]
workers_dev = false


[env.production.vars]
ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "big"
database_id = "25ae5f05-9c48-4851-bf88-d28ba703b7eb"
preview_database_id = "25ae5f05-9c48-4851-bf88-d28ba703b7eb"
migrations_table = "migrations"
migrations_dir = "migrations"

[[r2_buckets]]
binding = 'USER_FILES'
bucket_name = 'user-files'


[durable_objects]
bindings = [
  { name = "REFRESH_TOKEN_STORAGE", class_name = "src/durable-objects/refresh-token.ts" }
]
