name = "big-auth"

compatibility_date = "2024-05-11"
route = "https://dev.iambig.ai/*"


main = "./src/index.ts"
logpush = true
tail_consumers = [{ service = "big-auth-tail" }]
kv_namespaces = [
	{ binding = "FILES_KV", id = "f6c5cd0496ad436d84882f01db59ef76", preview_id = "52a4091c72f743fc9b1c3cfe6f647277" },
]

workers_dev = true
[vars]
TWILIO_SERVICE_SID = 'VA57c51729f8befa0fd3f10073bc2edc1c'
ORIGIN = "https://dev.iambig.ai"
AI_AVATAR_URL = "https://dev.iambig.ai/public/23d6658a2a06538a1b04c56aeb1f1874815f6a7f3853481a29609ca46de57bef"
ENV = "development"

[placement]
mode = "off"

[[d1_databases]]
binding = "DB"
database_name = "imbig"
database_id = "50a83409-8f4f-49ad-af14-573f33b0b91d"
migrations_table = "migrations"
migrations_dir = "src/db/migrations"

[[r2_buckets]]
binding = 'USER_FILES'
bucket_name = 'user-files'
preview_bucket_name = 'user-files-preview'

[[queues.producers]]
queue = "push-queue"
binding = "PUSH_QUEUE"


[durable_objects]
bindings = [
	{ name = "REFRESH_TOKEN_DO", class_name = "RefreshTokenDO" },
	{ name = "GROUP_CHATS_DO", class_name = "GroupChatsDO" },
	{ name = "USER_MESSAGING_DO", class_name = "UserMessagingDO" },
	{ name = "DIALOG_DO", class_name = "DialogsDO" },
	{ name = "GPT_DO", class_name = "ChatGptDO" },
	{ name = "PUSH_TOKEN_DO", class_name = "PushDO" },
]


[[migrations]]
tag = "v54"
deleted_classes = ["UserMessagingDO", "DialogsDO", "GroupChatsDO", "ChatGptDO"]
[[migrations]]
tag = "v55"
new_classes = ["UserMessagingDO", "DialogsDO", "GroupChatsDO", "ChatGptDO"]
